version: "3.7"
services:
  backend:
    build:
      dockerfile: Dockerfile
      target: release
    ports:
      - "3306:3306"
    networks:
      - express-typescript

networks:
  express-typescript:
